// <auto-generated />
using System;
using AMS_data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS_data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS_data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OrganizacionaJedinicaId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkladisteId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AMS_data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AMS_data.Entities.Evidence.EvidenceDeposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AgeBandLookupId")
                        .HasColumnType("int");

                    b.Property<string>("CaseInfoFolderPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaseTypeLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DepositLocationLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("EvidenceIndicatorLookupId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandlingOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCoCriminalOffence")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGenderBasedViolence")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<string>("PersonalIdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SexLookupId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StorageOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StorageOrderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmittedByOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgeBandLookupId");

                    b.HasIndex("CaseTypeLookupId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepositLocationLookupId");

                    b.HasIndex("EvidenceIndicatorLookupId");

                    b.HasIndex("SexLookupId");

                    b.ToTable("EvidenceDeposits");
                });

            modelBuilder.Entity("AMS_data.Entities.Evidence.EvidenceDepositItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvidenceDepositId")
                        .HasColumnType("int");

                    b.Property<int?>("EvidenceWeaponLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("EvidenceWeaponTypeLookupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LinkedWeaponId")
                        .HasColumnType("int");

                    b.Property<string>("MarkingText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeaponItemTypeLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponLegalityLookupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceDepositId");

                    b.HasIndex("EvidenceWeaponLookupId");

                    b.HasIndex("EvidenceWeaponTypeLookupId");

                    b.HasIndex("LinkedWeaponId");

                    b.HasIndex("WeaponItemTypeLookupId");

                    b.HasIndex("WeaponLegalityLookupId");

                    b.ToTable("EvidenceDepositItems");
                });

            modelBuilder.Entity("AMS_data.Entities.Evidence.EvidenceMoveHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvidenceDepositId")
                        .HasColumnType("int");

                    b.Property<int?>("EvidenceDepositItemId")
                        .HasColumnType("int");

                    b.Property<int?>("FromLocationLookupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MoveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MovePurposeLookupId")
                        .HasColumnType("int");

                    b.Property<string>("MovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToLocationLookupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceDepositId");

                    b.HasIndex("EvidenceDepositItemId");

                    b.HasIndex("FromLocationLookupId");

                    b.HasIndex("MovePurposeLookupId");

                    b.HasIndex("ToLocationLookupId");

                    b.ToTable("EvidenceMoveHistories");
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LookupCategories");
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("DoNotDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LookupCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentLookupItemId")
                        .HasColumnType("int");

                    b.Property<bool>("UserDefinedSort")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LookupCategoryId");

                    b.HasIndex("ParentLookupItemId");

                    b.ToTable("LookupItems");
                });

            modelBuilder.Entity("AMS_data.Entities.Narcotics.NarcoticsDeposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseInfoFolderPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaseTypeLookupId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmStorageOrderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DepositLocationLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DestructionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DestructionOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestructionOrderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EvidenceIndicatorLookupId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ForensicReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ForensicReportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandlingOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<string>("LinkToOrderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OUPerformedSeizureLookupId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalIdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StorageOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StorageOrderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmittedByOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("VerdictDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerdictNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseTypeLookupId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepositLocationLookupId");

                    b.HasIndex("EvidenceIndicatorLookupId");

                    b.HasIndex("OUPerformedSeizureLookupId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("NarcoticsDeposits");
                });

            modelBuilder.Entity("AMS_data.Entities.Narcotics.NarcoticsDepositItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompositionLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NarcoticsDepositId")
                        .HasColumnType("int");

                    b.Property<int?>("NarcoticsTypeLookupId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("QuantityUnitLookupId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompositionLookupId");

                    b.HasIndex("NarcoticsDepositId");

                    b.HasIndex("NarcoticsTypeLookupId");

                    b.HasIndex("QuantityUnitLookupId");

                    b.ToTable("NarcoticsDepositItems");
                });

            modelBuilder.Entity("AMS_data.Entities.Narcotics.NarcoticsMoveHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromLocationLookupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MoveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MovePurposeLookupId")
                        .HasColumnType("int");

                    b.Property<string>("MovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NarcoticsDepositId")
                        .HasColumnType("int");

                    b.Property<int?>("NarcoticsDepositItemId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToLocationLookupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromLocationLookupId");

                    b.HasIndex("MovePurposeLookupId");

                    b.HasIndex("NarcoticsDepositId");

                    b.HasIndex("NarcoticsDepositItemId");

                    b.HasIndex("ToLocationLookupId");

                    b.ToTable("NarcoticsMoveHistories");
                });

            modelBuilder.Entity("AMS_data.Entities.OrganizacionaJedinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivna")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrganizacioneJedinice");
                });

            modelBuilder.Entity("AMS_data.Entities.Skladiste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivno")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizacionaJedinicaId")
                        .HasColumnType("int");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionaJedinicaId");

                    b.ToTable("Skladista");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.Caliber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Calibers");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryLookupId");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.MarkingLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HeightMm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WidthMm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MarkingLayouts");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.MarkingLayoutObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("FontSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBold")
                        .HasColumnType("bit");

                    b.Property<int>("MarkingLayoutId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rotation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StrokeWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("X")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Y")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarkingLayoutId");

                    b.ToTable("MarkingLayoutObjects");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.SavedWeaponQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SavedWeaponQueries");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarrelMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookkeepingByLookupId")
                        .HasColumnType("int");

                    b.Property<string>("ButtstockMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaliberId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfOwnership")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DonorAgencyLookupId")
                        .HasColumnType("int");

                    b.Property<string>("DonorContractNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactorySerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GovernmentAgencyLookupId")
                        .HasColumnType("int");

                    b.Property<string>("HolderInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdTypeLookupId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMarked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProspective")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufactureCountryLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkLocationLookupId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginIndicatorLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalLocationLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalStateLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("RegionLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlideMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StockLookupId")
                        .HasColumnType("int");

                    b.Property<bool>("TempStock")
                        .HasColumnType("bit");

                    b.Property<int?>("UnitLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeaponModelId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponStateLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookkeepingByLookupId");

                    b.HasIndex("CaliberId");

                    b.HasIndex("CountryLookupId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("DonorAgencyLookupId");

                    b.HasIndex("GovernmentAgencyLookupId");

                    b.HasIndex("IdTypeLookupId");

                    b.HasIndex("ManufactureCountryLookupId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MarkLocationLookupId");

                    b.HasIndex("OriginIndicatorLookupId");

                    b.HasIndex("OriginalLocationLookupId");

                    b.HasIndex("OriginalStateLookupId");

                    b.HasIndex("RegionLookupId");

                    b.HasIndex("StockLookupId");

                    b.HasIndex("UnitLookupId");

                    b.HasIndex("WeaponModelId");

                    b.HasIndex("WeaponStateLookupId");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CheckStateLookupId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckStateLookupId");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponChecks");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponMarkingJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caliber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataMatrixValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactorySerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JobDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarkingLayoutId")
                        .HasColumnType("int");

                    b.Property<string>("MarkingText1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingText2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingText3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<string>("WeaponModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeaponType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarkingLayoutId");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponMarkingJobs");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaliberId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeaponTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaliberId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("WeaponModels");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthMoveNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuthorisedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthorisedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorisedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndUserCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MoveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoveOrdinalNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovementActionLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("NewLocationLookupId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreparedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserOrgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovementActionLookupId");

                    b.HasIndex("NewLocationLookupId");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponMoves");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeaponStatuses");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeaponTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AMS_data.Entities.Evidence.EvidenceDeposit", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "AgeBandLookup")
                        .WithMany()
                        .HasForeignKey("AgeBandLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "CaseTypeLookup")
                        .WithMany()
                        .HasForeignKey("CaseTypeLookupId");

                    b.HasOne("AMS_data.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "DepositLocationLookup")
                        .WithMany()
                        .HasForeignKey("DepositLocationLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "EvidenceIndicatorLookup")
                        .WithMany()
                        .HasForeignKey("EvidenceIndicatorLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "SexLookup")
                        .WithMany()
                        .HasForeignKey("SexLookupId");

                    b.Navigation("AgeBandLookup");

                    b.Navigation("CaseTypeLookup");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DepositLocationLookup");

                    b.Navigation("EvidenceIndicatorLookup");

                    b.Navigation("SexLookup");
                });

            modelBuilder.Entity("AMS_data.Entities.Evidence.EvidenceDepositItem", b =>
                {
                    b.HasOne("AMS_data.Entities.Evidence.EvidenceDeposit", "EvidenceDeposit")
                        .WithMany("Items")
                        .HasForeignKey("EvidenceDepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "EvidenceWeaponLookup")
                        .WithMany()
                        .HasForeignKey("EvidenceWeaponLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "EvidenceWeaponTypeLookup")
                        .WithMany()
                        .HasForeignKey("EvidenceWeaponTypeLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.Weapon", "LinkedWeapon")
                        .WithMany()
                        .HasForeignKey("LinkedWeaponId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "WeaponItemTypeLookup")
                        .WithMany()
                        .HasForeignKey("WeaponItemTypeLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "WeaponLegalityLookup")
                        .WithMany()
                        .HasForeignKey("WeaponLegalityLookupId");

                    b.Navigation("EvidenceDeposit");

                    b.Navigation("EvidenceWeaponLookup");

                    b.Navigation("EvidenceWeaponTypeLookup");

                    b.Navigation("LinkedWeapon");

                    b.Navigation("WeaponItemTypeLookup");

                    b.Navigation("WeaponLegalityLookup");
                });

            modelBuilder.Entity("AMS_data.Entities.Evidence.EvidenceMoveHistory", b =>
                {
                    b.HasOne("AMS_data.Entities.Evidence.EvidenceDeposit", "EvidenceDeposit")
                        .WithMany("MoveHistories")
                        .HasForeignKey("EvidenceDepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS_data.Entities.Evidence.EvidenceDepositItem", "EvidenceDepositItem")
                        .WithMany()
                        .HasForeignKey("EvidenceDepositItemId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "FromLocationLookup")
                        .WithMany()
                        .HasForeignKey("FromLocationLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "MovePurposeLookup")
                        .WithMany()
                        .HasForeignKey("MovePurposeLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "ToLocationLookup")
                        .WithMany()
                        .HasForeignKey("ToLocationLookupId");

                    b.Navigation("EvidenceDeposit");

                    b.Navigation("EvidenceDepositItem");

                    b.Navigation("FromLocationLookup");

                    b.Navigation("MovePurposeLookup");

                    b.Navigation("ToLocationLookup");
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupItem", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupCategory", "LookupCategory")
                        .WithMany("Items")
                        .HasForeignKey("LookupCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "ParentLookupItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentLookupItemId");

                    b.Navigation("LookupCategory");

                    b.Navigation("ParentLookupItem");
                });

            modelBuilder.Entity("AMS_data.Entities.Narcotics.NarcoticsDeposit", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "CaseTypeLookup")
                        .WithMany()
                        .HasForeignKey("CaseTypeLookupId");

                    b.HasOne("AMS_data.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "DepositLocationLookup")
                        .WithMany()
                        .HasForeignKey("DepositLocationLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "EvidenceIndicatorLookup")
                        .WithMany()
                        .HasForeignKey("EvidenceIndicatorLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "OUPerformedSeizureLookup")
                        .WithMany()
                        .HasForeignKey("OUPerformedSeizureLookupId");

                    b.HasOne("AMS_data.Entities.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CaseTypeLookup");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DepositLocationLookup");

                    b.Navigation("EvidenceIndicatorLookup");

                    b.Navigation("OUPerformedSeizureLookup");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AMS_data.Entities.Narcotics.NarcoticsDepositItem", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "CompositionLookup")
                        .WithMany()
                        .HasForeignKey("CompositionLookupId");

                    b.HasOne("AMS_data.Entities.Narcotics.NarcoticsDeposit", "NarcoticsDeposit")
                        .WithMany("Items")
                        .HasForeignKey("NarcoticsDepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "NarcoticsTypeLookup")
                        .WithMany()
                        .HasForeignKey("NarcoticsTypeLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "QuantityUnitLookup")
                        .WithMany()
                        .HasForeignKey("QuantityUnitLookupId");

                    b.Navigation("CompositionLookup");

                    b.Navigation("NarcoticsDeposit");

                    b.Navigation("NarcoticsTypeLookup");

                    b.Navigation("QuantityUnitLookup");
                });

            modelBuilder.Entity("AMS_data.Entities.Narcotics.NarcoticsMoveHistory", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "FromLocationLookup")
                        .WithMany()
                        .HasForeignKey("FromLocationLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "MovePurposeLookup")
                        .WithMany()
                        .HasForeignKey("MovePurposeLookupId");

                    b.HasOne("AMS_data.Entities.Narcotics.NarcoticsDeposit", "NarcoticsDeposit")
                        .WithMany("MoveHistories")
                        .HasForeignKey("NarcoticsDepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS_data.Entities.Narcotics.NarcoticsDepositItem", "NarcoticsDepositItem")
                        .WithMany()
                        .HasForeignKey("NarcoticsDepositItemId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "ToLocationLookup")
                        .WithMany()
                        .HasForeignKey("ToLocationLookupId");

                    b.Navigation("FromLocationLookup");

                    b.Navigation("MovePurposeLookup");

                    b.Navigation("NarcoticsDeposit");

                    b.Navigation("NarcoticsDepositItem");

                    b.Navigation("ToLocationLookup");
                });

            modelBuilder.Entity("AMS_data.Entities.Skladiste", b =>
                {
                    b.HasOne("AMS_data.Entities.OrganizacionaJedinica", "OrganizacionaJedinica")
                        .WithMany()
                        .HasForeignKey("OrganizacionaJedinicaId");

                    b.Navigation("OrganizacionaJedinica");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.Manufacturer", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "CountryLookup")
                        .WithMany()
                        .HasForeignKey("CountryLookupId");

                    b.Navigation("CountryLookup");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.MarkingLayoutObject", b =>
                {
                    b.HasOne("AMS_data.Entities.Weapons.MarkingLayout", "MarkingLayout")
                        .WithMany("Objects")
                        .HasForeignKey("MarkingLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkingLayout");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.Weapon", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "BookkeepingByLookup")
                        .WithMany()
                        .HasForeignKey("BookkeepingByLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.Caliber", "Caliber")
                        .WithMany()
                        .HasForeignKey("CaliberId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "CountryLookup")
                        .WithMany()
                        .HasForeignKey("CountryLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.WeaponStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "DonorAgencyLookup")
                        .WithMany()
                        .HasForeignKey("DonorAgencyLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "GovernmentAgencyLookup")
                        .WithMany()
                        .HasForeignKey("GovernmentAgencyLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "IdTypeLookup")
                        .WithMany()
                        .HasForeignKey("IdTypeLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "ManufactureCountryLookup")
                        .WithMany()
                        .HasForeignKey("ManufactureCountryLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "MarkLocationLookup")
                        .WithMany()
                        .HasForeignKey("MarkLocationLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "OriginIndicatorLookup")
                        .WithMany()
                        .HasForeignKey("OriginIndicatorLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "OriginalLocationLookup")
                        .WithMany()
                        .HasForeignKey("OriginalLocationLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "OriginalStateLookup")
                        .WithMany()
                        .HasForeignKey("OriginalStateLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "RegionLookup")
                        .WithMany()
                        .HasForeignKey("RegionLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "StockLookup")
                        .WithMany()
                        .HasForeignKey("StockLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "UnitLookup")
                        .WithMany()
                        .HasForeignKey("UnitLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.WeaponModel", "WeaponModel")
                        .WithMany()
                        .HasForeignKey("WeaponModelId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "WeaponStateLookup")
                        .WithMany()
                        .HasForeignKey("WeaponStateLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.WeaponType", "WeaponType")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId");

                    b.Navigation("BookkeepingByLookup");

                    b.Navigation("Caliber");

                    b.Navigation("CountryLookup");

                    b.Navigation("CurrentStatus");

                    b.Navigation("DonorAgencyLookup");

                    b.Navigation("GovernmentAgencyLookup");

                    b.Navigation("IdTypeLookup");

                    b.Navigation("ManufactureCountryLookup");

                    b.Navigation("Manufacturer");

                    b.Navigation("MarkLocationLookup");

                    b.Navigation("OriginIndicatorLookup");

                    b.Navigation("OriginalLocationLookup");

                    b.Navigation("OriginalStateLookup");

                    b.Navigation("RegionLookup");

                    b.Navigation("StockLookup");

                    b.Navigation("UnitLookup");

                    b.Navigation("WeaponModel");

                    b.Navigation("WeaponStateLookup");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponCheck", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "CheckStateLookup")
                        .WithMany()
                        .HasForeignKey("CheckStateLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckStateLookup");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponMarkingJob", b =>
                {
                    b.HasOne("AMS_data.Entities.Weapons.MarkingLayout", "MarkingLayout")
                        .WithMany()
                        .HasForeignKey("MarkingLayoutId");

                    b.HasOne("AMS_data.Entities.Weapons.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkingLayout");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponModel", b =>
                {
                    b.HasOne("AMS_data.Entities.Weapons.Caliber", "Caliber")
                        .WithMany()
                        .HasForeignKey("CaliberId");

                    b.HasOne("AMS_data.Entities.Weapons.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("AMS_data.Entities.Weapons.WeaponType", "WeaponType")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId");

                    b.Navigation("Caliber");

                    b.Navigation("Manufacturer");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponMove", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "MovementActionLookup")
                        .WithMany()
                        .HasForeignKey("MovementActionLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "NewLocationLookup")
                        .WithMany()
                        .HasForeignKey("NewLocationLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovementActionLookup");

                    b.Navigation("NewLocationLookup");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AMS_data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AMS_data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS_data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AMS_data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS_data.Entities.Evidence.EvidenceDeposit", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MoveHistories");
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("AMS_data.Entities.Narcotics.NarcoticsDeposit", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MoveHistories");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.MarkingLayout", b =>
                {
                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
