// <auto-generated />
using System;
using AMS_data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMS_data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMS_data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("OrganizacionaJedinicaId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkladisteId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AMS_data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LookupCategories");
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("DoNotDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LookupCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentLookupItemId")
                        .HasColumnType("int");

                    b.Property<bool>("UserDefinedSort")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LookupCategoryId");

                    b.HasIndex("ParentLookupItemId");

                    b.ToTable("LookupItems");
                });

            modelBuilder.Entity("AMS_data.Entities.OrganizacionaJedinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivna")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrganizacioneJedinice");
                });

            modelBuilder.Entity("AMS_data.Entities.Skladiste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivno")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizacionaJedinicaId")
                        .HasColumnType("int");

                    b.Property<string>("Sifra")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionaJedinicaId");

                    b.ToTable("Skladista");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.Caliber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Calibers");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarrelMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookkeepingByLookupId")
                        .HasColumnType("int");

                    b.Property<string>("ButtstockMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaliberId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmSerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfOwnership")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DonorAgencyLookupId")
                        .HasColumnType("int");

                    b.Property<string>("DonorContractNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactorySerial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GovernmentAgencyLookupId")
                        .HasColumnType("int");

                    b.Property<string>("HolderInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdTypeLookupId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMarked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProspective")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufactureCountryLookupId")
                        .HasColumnType("int");

                    b.Property<string>("ManufactureDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkLocationLookupId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginIndicatorLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalLocationLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalStateLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("RegionLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlideMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StockLookupId")
                        .HasColumnType("int");

                    b.Property<bool>("TempStock")
                        .HasColumnType("bit");

                    b.Property<int?>("UnitLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeaponModelId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponStateLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookkeepingByLookupId");

                    b.HasIndex("CaliberId");

                    b.HasIndex("CountryLookupId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("DonorAgencyLookupId");

                    b.HasIndex("GovernmentAgencyLookupId");

                    b.HasIndex("IdTypeLookupId");

                    b.HasIndex("ManufactureCountryLookupId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MarkLocationLookupId");

                    b.HasIndex("OriginIndicatorLookupId");

                    b.HasIndex("OriginalLocationLookupId");

                    b.HasIndex("OriginalStateLookupId");

                    b.HasIndex("RegionLookupId");

                    b.HasIndex("StockLookupId");

                    b.HasIndex("UnitLookupId");

                    b.HasIndex("WeaponModelId");

                    b.HasIndex("WeaponStateLookupId");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaliberId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeaponTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaliberId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("WeaponModels");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeaponStatuses");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeaponTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupItem", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupCategory", "LookupCategory")
                        .WithMany("Items")
                        .HasForeignKey("LookupCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "ParentLookupItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentLookupItemId");

                    b.Navigation("LookupCategory");

                    b.Navigation("ParentLookupItem");
                });

            modelBuilder.Entity("AMS_data.Entities.Skladiste", b =>
                {
                    b.HasOne("AMS_data.Entities.OrganizacionaJedinica", "OrganizacionaJedinica")
                        .WithMany()
                        .HasForeignKey("OrganizacionaJedinicaId");

                    b.Navigation("OrganizacionaJedinica");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.Weapon", b =>
                {
                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "BookkeepingByLookup")
                        .WithMany()
                        .HasForeignKey("BookkeepingByLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.Caliber", "Caliber")
                        .WithMany()
                        .HasForeignKey("CaliberId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "CountryLookup")
                        .WithMany()
                        .HasForeignKey("CountryLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.WeaponStatus", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "DonorAgencyLookup")
                        .WithMany()
                        .HasForeignKey("DonorAgencyLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "GovernmentAgencyLookup")
                        .WithMany()
                        .HasForeignKey("GovernmentAgencyLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "IdTypeLookup")
                        .WithMany()
                        .HasForeignKey("IdTypeLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "ManufactureCountryLookup")
                        .WithMany()
                        .HasForeignKey("ManufactureCountryLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "MarkLocationLookup")
                        .WithMany()
                        .HasForeignKey("MarkLocationLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "OriginIndicatorLookup")
                        .WithMany()
                        .HasForeignKey("OriginIndicatorLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "OriginalLocationLookup")
                        .WithMany()
                        .HasForeignKey("OriginalLocationLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "OriginalStateLookup")
                        .WithMany()
                        .HasForeignKey("OriginalStateLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "RegionLookup")
                        .WithMany()
                        .HasForeignKey("RegionLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "StockLookup")
                        .WithMany()
                        .HasForeignKey("StockLookupId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "UnitLookup")
                        .WithMany()
                        .HasForeignKey("UnitLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.WeaponModel", "WeaponModel")
                        .WithMany()
                        .HasForeignKey("WeaponModelId");

                    b.HasOne("AMS_data.Entities.Lookups.LookupItem", "WeaponStateLookup")
                        .WithMany()
                        .HasForeignKey("WeaponStateLookupId");

                    b.HasOne("AMS_data.Entities.Weapons.WeaponType", "WeaponType")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId");

                    b.Navigation("BookkeepingByLookup");

                    b.Navigation("Caliber");

                    b.Navigation("CountryLookup");

                    b.Navigation("CurrentStatus");

                    b.Navigation("DonorAgencyLookup");

                    b.Navigation("GovernmentAgencyLookup");

                    b.Navigation("IdTypeLookup");

                    b.Navigation("ManufactureCountryLookup");

                    b.Navigation("Manufacturer");

                    b.Navigation("MarkLocationLookup");

                    b.Navigation("OriginIndicatorLookup");

                    b.Navigation("OriginalLocationLookup");

                    b.Navigation("OriginalStateLookup");

                    b.Navigation("RegionLookup");

                    b.Navigation("StockLookup");

                    b.Navigation("UnitLookup");

                    b.Navigation("WeaponModel");

                    b.Navigation("WeaponStateLookup");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("AMS_data.Entities.Weapons.WeaponModel", b =>
                {
                    b.HasOne("AMS_data.Entities.Weapons.Caliber", "Caliber")
                        .WithMany()
                        .HasForeignKey("CaliberId");

                    b.HasOne("AMS_data.Entities.Weapons.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.HasOne("AMS_data.Entities.Weapons.WeaponType", "WeaponType")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId");

                    b.Navigation("Caliber");

                    b.Navigation("Manufacturer");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AMS_data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AMS_data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMS_data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AMS_data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AMS_data.Entities.Lookups.LookupItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
