//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset_management_Web_Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class bs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal bs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asset_management_Web_Core.Resources.bs", typeof(bs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcije.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivan.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivna oružja.
        /// </summary>
        public static string ActiveWeapons {
            get {
                return ResourceManager.GetString("ActiveWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kalibar.
        /// </summary>
        public static string AddCaliber {
            get {
                return ResourceManager.GetString("AddCaliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj stavku.
        /// </summary>
        public static string AddLookupItem {
            get {
                return ResourceManager.GetString("AddLookupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj proizvođača.
        /// </summary>
        public static string AddManufacturer {
            get {
                return ResourceManager.GetString("AddManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj novo.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj model oružja.
        /// </summary>
        public static string AddWeaponModel {
            get {
                return ResourceManager.GetString("AddWeaponModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj status oružja.
        /// </summary>
        public static string AddWeaponStatus {
            get {
                return ResourceManager.GetString("AddWeaponStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj tip oružja.
        /// </summary>
        public static string AddWeaponType {
            get {
                return ResourceManager.GetString("AddWeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starosna grupa.
        /// </summary>
        public static string AgeBand {
            get {
                return ResourceManager.GetString("AgeBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svi statusi.
        /// </summary>
        public static string AllStatuses {
            get {
                return ResourceManager.GetString("AllStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik.
        /// </summary>
        public static string AMSUser {
            get {
                return ResourceManager.GetString("AMSUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Stock.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizacija pomjeranja oružja.
        /// </summary>
        public static string AuthoriseWeaponMove {
            get {
                return ResourceManager.GetString("AuthoriseWeaponMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad na šifarnike.
        /// </summary>
        public static string BackToDataCapture {
            get {
                return ResourceManager.GetString("BackToDataCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad na listu.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka cijevi.
        /// </summary>
        public static string BarrelMark {
            get {
                return ResourceManager.GetString("BarrelMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knjigovodstveno vodi.
        /// </summary>
        public static string BookkeepingBy {
            get {
                return ResourceManager.GetString("BookkeepingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka kundaka.
        /// </summary>
        public static string ButtstockMark {
            get {
                return ResourceManager.GetString("ButtstockMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalibar.
        /// </summary>
        public static string Caliber {
            get {
                return ResourceManager.GetString("Caliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite osnovne podatke o kalibru..
        /// </summary>
        public static string CaliberFormDescription {
            get {
                return ResourceManager.GetString("CaliberFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalibri.
        /// </summary>
        public static string Calibers {
            get {
                return ResourceManager.GetString("Calibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje šifarnikom kalibara..
        /// </summary>
        public static string CalibersDescription {
            get {
                return ResourceManager.GetString("CalibersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta slučaja.
        /// </summary>
        public static string CaseType {
            get {
                return ResourceManager.GetString("CaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum provjere.
        /// </summary>
        public static string CheckDate {
            get {
                return ResourceManager.GetString("CheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historija provjera.
        /// </summary>
        public static string CheckHistory {
            get {
                return ResourceManager.GetString("CheckHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanje provjere.
        /// </summary>
        public static string CheckState {
            get {
                return ResourceManager.GetString("CheckState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provjera statusa oružja.
        /// </summary>
        public static string CheckWeaponStatus {
            get {
                return ResourceManager.GetString("CheckWeaponStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provjera, održavanje i historija stanja registrovanog oružja..
        /// </summary>
        public static string CheckWeaponStatusDescription {
            get {
                return ResourceManager.GetString("CheckWeaponStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda serijskog broja.
        /// </summary>
        public static string ConfirmSerial {
            get {
                return ResourceManager.GetString("ConfirmSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj korisnika.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna slika.
        /// </summary>
        public static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled ključnih informacija i brzih akcija sistema..
        /// </summary>
        public static string DashboardDescription {
            get {
                return ResourceManager.GetString("DashboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos podataka.
        /// </summary>
        public static string DataCapture {
            get {
                return ResourceManager.GetString("DataCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centralno mjesto za upravljanje šifarnicima i podacima koje sistem koristi u formama..
        /// </summary>
        public static string DataCaptureDescription {
            get {
                return ResourceManager.GetString("DataCaptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vlasništva.
        /// </summary>
        public static string DateOfOwnership {
            get {
                return ResourceManager.GetString("DateOfOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redoslijed prikaza.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum donacije.
        /// </summary>
        public static string DonationDate {
            get {
                return ResourceManager.GetString("DonationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donacija / privremena zaliha.
        /// </summary>
        public static string DonationTemporaryStock {
            get {
                return ResourceManager.GetString("DonationTemporaryStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donatorska agencija.
        /// </summary>
        public static string DonorAgency {
            get {
                return ResourceManager.GetString("DonorAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ugovora donatora.
        /// </summary>
        public static string DonorContractNo {
            get {
                return ResourceManager.GetString("DonorContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmijeni.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena kalibra.
        /// </summary>
        public static string EditCaliber {
            get {
                return ResourceManager.GetString("EditCaliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena stavke.
        /// </summary>
        public static string EditLookupItem {
            get {
                return ResourceManager.GetString("EditLookupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena proizvođača.
        /// </summary>
        public static string EditManufacturer {
            get {
                return ResourceManager.GetString("EditManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena korisnika.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena osnovnih podataka, role i pristupa korisnika..
        /// </summary>
        public static string EditUserDescription {
            get {
                return ResourceManager.GetString("EditUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena modela oružja.
        /// </summary>
        public static string EditWeaponModel {
            get {
                return ResourceManager.GetString("EditWeaponModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena statusa oružja.
        /// </summary>
        public static string EditWeaponStatus {
            get {
                return ResourceManager.GetString("EditWeaponStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmjena tipa oružja.
        /// </summary>
        public static string EditWeaponType {
            get {
                return ResourceManager.GetString("EditWeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite šifru.
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite državu.
        /// </summary>
        public static string EnterCountry {
            get {
                return ResourceManager.GetString("EnterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite opis.
        /// </summary>
        public static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite redoslijed prikaza.
        /// </summary>
        public static string EnterDisplayOrder {
            get {
                return ResourceManager.GetString("EnterDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime.
        /// </summary>
        public static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite prezime.
        /// </summary>
        public static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite naziv.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite lozinku.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokazi.
        /// </summary>
        public static string Evidence {
            get {
                return ResourceManager.GetString("Evidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o dokazima.
        /// </summary>
        public static string EvidenceData {
            get {
                return ResourceManager.GetString("EvidenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifarnici za dokaze, predmete, oružje, lokacije depozita i vrste slučajeva..
        /// </summary>
        public static string EvidenceDataDescription {
            get {
                return ResourceManager.GetString("EvidenceDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacije depozita dokaza.
        /// </summary>
        public static string EvidenceDepositLocation {
            get {
                return ResourceManager.GetString("EvidenceDepositLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indikatori dokaza.
        /// </summary>
        public static string EvidenceIndicator {
            get {
                return ResourceManager.GetString("EvidenceIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokazno oružje.
        /// </summary>
        public static string EvidenceWeapon {
            get {
                return ResourceManager.GetString("EvidenceWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrste dokaznog oružja.
        /// </summary>
        public static string EvidenceWeaponType {
            get {
                return ResourceManager.GetString("EvidenceWeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabrički serijski broj.
        /// </summary>
        public static string FactorySerial {
            get {
                return ResourceManager.GetString("FactorySerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtriraj.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vladine agencije.
        /// </summary>
        public static string GovernmentAgencies {
            get {
                return ResourceManager.GetString("GovernmentAgencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vladina agencija.
        /// </summary>
        public static string GovernmentAgency {
            get {
                return ResourceManager.GetString("GovernmentAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o držaocu.
        /// </summary>
        public static string HolderInfo {
            get {
                return ResourceManager.GetString("HolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početna.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikacija.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID broj.
        /// </summary>
        public static string IdNo {
            get {
                return ResourceManager.GetString("IdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tip ID-a.
        /// </summary>
        public static string IdType {
            get {
                return ResourceManager.GetString("IdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventurni broj.
        /// </summary>
        public static string InventoryNo {
            get {
                return ResourceManager.GetString("InventoryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivan.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacije.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavke šifarnika.
        /// </summary>
        public static string LookupItems {
            get {
                return ResourceManager.GetString("LookupItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje vrijednostima za odabrani šifarnik..
        /// </summary>
        public static string LookupItemsDescription {
            get {
                return ResourceManager.GetString("LookupItemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum/godina proizvodnje.
        /// </summary>
        public static string ManufactureDate {
            get {
                return ResourceManager.GetString("ManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proizvođač.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država proizvođača.
        /// </summary>
        public static string ManufacturerCountry {
            get {
                return ResourceManager.GetString("ManufacturerCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite osnovne podatke o proizvođaču..
        /// </summary>
        public static string ManufacturerFormDescription {
            get {
                return ResourceManager.GetString("ManufacturerFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proizvođači.
        /// </summary>
        public static string Manufacturers {
            get {
                return ResourceManager.GetString("Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje šifarnikom proizvođača oružja..
        /// </summary>
        public static string ManufacturersDescription {
            get {
                return ResourceManager.GetString("ManufacturersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina proizvodnje.
        /// </summary>
        public static string ManufactureYear {
            get {
                return ResourceManager.GetString("ManufactureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označeno oružje.
        /// </summary>
        public static string MarkedWeapons {
            get {
                return ResourceManager.GetString("MarkedWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacije obilježavanja.
        /// </summary>
        public static string MarkLocations {
            get {
                return ResourceManager.GetString("MarkLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika modela.
        /// </summary>
        public static string ModelImage {
            get {
                return ResourceManager.GetString("ModelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovlaštene osobe za pomjeranje.
        /// </summary>
        public static string MoveAuthoriserNames {
            get {
                return ResourceManager.GetString("MoveAuthoriserNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacije pomjerenog oružja.
        /// </summary>
        public static string MovedWeaponLocation {
            get {
                return ResourceManager.GetString("MovedWeaponLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svrha pomjeranja dokaza.
        /// </summary>
        public static string MoveEvidencePurpose {
            get {
                return ResourceManager.GetString("MoveEvidencePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcije kretanja.
        /// </summary>
        public static string MovementActions {
            get {
                return ResourceManager.GetString("MovementActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o kretanju.
        /// </summary>
        public static string MovementData {
            get {
                return ResourceManager.GetString("MovementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlozi, akcije i lokacije za prenos oružja..
        /// </summary>
        public static string MovementDataDescription {
            get {
                return ResourceManager.GetString("MovementDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlozi kretanja.
        /// </summary>
        public static string MovementReasons {
            get {
                return ResourceManager.GetString("MovementReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status pomjeranja.
        /// </summary>
        public static string MoveStatus {
            get {
                return ResourceManager.GetString("MoveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi korisnik.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Bez organizacione jedinice --.
        /// </summary>
        public static string NoOrganizationalUnit {
            get {
                return ResourceManager.GetString("NoOrganizationalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema pronađenih zapisa.
        /// </summary>
        public static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napomene.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Bez skladišta --.
        /// </summary>
        public static string NoWarehouse {
            get {
                return ResourceManager.GetString("NoWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizaciona jedinica.
        /// </summary>
        public static string OrganizationalUnit {
            get {
                return ResourceManager.GetString("OrganizationalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacione jedinice.
        /// </summary>
        public static string OrganizationalUnits {
            get {
                return ResourceManager.GetString("OrganizationalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacioni podaci.
        /// </summary>
        public static string OrganizationData {
            get {
                return ResourceManager.GetString("OrganizationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacione jedinice, skladišta i agencije..
        /// </summary>
        public static string OrganizationDataDescription {
            get {
                return ResourceManager.GetString("OrganizationDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originalna lokacija.
        /// </summary>
        public static string OriginalLocation {
            get {
                return ResourceManager.GetString("OriginalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originalne lokacije.
        /// </summary>
        public static string OriginalLocations {
            get {
                return ResourceManager.GetString("OriginalLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originalno stanje.
        /// </summary>
        public static string OriginalState {
            get {
                return ResourceManager.GetString("OriginalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originalna stanja.
        /// </summary>
        public static string OriginalStates {
            get {
                return ResourceManager.GetString("OriginalStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indikator porijekla.
        /// </summary>
        public static string OriginIndicator {
            get {
                return ResourceManager.GetString("OriginIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porijeklo i vlasništvo.
        /// </summary>
        public static string OriginOwnership {
            get {
                return ResourceManager.GetString("OriginOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizičke oznake.
        /// </summary>
        public static string PhysicalMarks {
            get {
                return ResourceManager.GetString("PhysicalMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priprema pomjeranja oružja.
        /// </summary>
        public static string PrepareWeaponMove {
            get {
                return ResourceManager.GetString("PrepareWeaponMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospektivno.
        /// </summary>
        public static string Prospective {
            get {
                return ResourceManager.GetString("Prospective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svrha korištenja.
        /// </summary>
        public static string PurposeOfUse {
            get {
                return ResourceManager.GetString("PurposeOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator izvještaja.
        /// </summary>
        public static string QueryGenerator {
            get {
                return ResourceManager.GetString("QueryGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brze akcije.
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadnje provjere.
        /// </summary>
        public static string RecentChecks {
            get {
                return ResourceManager.GetString("RecentChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadnje registracije oružja.
        /// </summary>
        public static string RecentWeapons {
            get {
                return ResourceManager.GetString("RecentWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regija.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registruj oružje.
        /// </summary>
        public static string RegisterWeapon {
            get {
                return ResourceManager.GetString("RegisterWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prva registracija i obilježavanje službenog oružja..
        /// </summary>
        public static string RegisterWeaponDescription {
            get {
                return ResourceManager.GetString("RegisterWeaponDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci registracije.
        /// </summary>
        public static string RegistrationData {
            get {
                return ResourceManager.GetString("RegistrationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum registracije.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj registracije.
        /// </summary>
        public static string RegistrationNo {
            get {
                return ResourceManager.GetString("RegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetuj.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rola.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj izmjene.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj oružje.
        /// </summary>
        public static string SaveWeapon {
            get {
                return ResourceManager.GetString("SaveWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcije pretrage.
        /// </summary>
        public static string SearchOptions {
            get {
                return ResourceManager.GetString("SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga po registraciji, serijskom broju, inventaru ili modelu.
        /// </summary>
        public static string SearchWeaponPlaceholder {
            get {
                return ResourceManager.GetString("SearchWeaponPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberi.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Odaberi kalibar --.
        /// </summary>
        public static string SelectCaliber {
            get {
                return ResourceManager.GetString("SelectCaliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Odaberi državu --.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrano oružje.
        /// </summary>
        public static string SelectedWeapon {
            get {
                return ResourceManager.GetString("SelectedWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Odaberi proizvođača --.
        /// </summary>
        public static string SelectManufacturer {
            get {
                return ResourceManager.GetString("SelectManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Odaberi --.
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Odaberi rolu --.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite oružje iz liste za unos provjere..
        /// </summary>
        public static string SelectWeaponFromList {
            get {
                return ResourceManager.GetString("SelectWeaponFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Odaberi model oružja --.
        /// </summary>
        public static string SelectWeaponModel {
            get {
                return ResourceManager.GetString("SelectWeaponModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Odaberi tip oružja --.
        /// </summary>
        public static string SelectWeaponType {
            get {
                return ResourceManager.GetString("SelectWeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spol.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka zatvarača.
        /// </summary>
        public static string SlideMark {
            get {
                return ResourceManager.GetString("SlideMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanje.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status i dodatni podaci.
        /// </summary>
        public static string StatusAndAdditional {
            get {
                return ResourceManager.GetString("StatusAndAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaliha.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privremena zaliha.
        /// </summary>
        public static string TempStock {
            get {
                return ResourceManager.GetString("TempStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno provjera.
        /// </summary>
        public static string TotalChecks {
            get {
                return ResourceManager.GetString("TotalChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupno oružja.
        /// </summary>
        public static string TotalWeapons {
            get {
                return ResourceManager.GetString("TotalWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedinica.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neoznačeno oružje.
        /// </summary>
        public static string UnmarkedWeapons {
            get {
                return ResourceManager.GetString("UnmarkedWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnici.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladište.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladišta.
        /// </summary>
        public static string Warehouses {
            get {
                return ResourceManager.GetString("Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos provjere.
        /// </summary>
        public static string WeaponCheckForm {
            get {
                return ResourceManager.GetString("WeaponCheckForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci o oružju.
        /// </summary>
        public static string WeaponData {
            get {
                return ResourceManager.GetString("WeaponData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi, proizvođači, kalibri, modeli i statusi oružja..
        /// </summary>
        public static string WeaponDataDescription {
            get {
                return ResourceManager.GetString("WeaponDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identitet oružja.
        /// </summary>
        public static string WeaponIdentity {
            get {
                return ResourceManager.GetString("WeaponIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip oružja.
        /// </summary>
        public static string WeaponItemType {
            get {
                return ResourceManager.GetString("WeaponItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legalnost oružja.
        /// </summary>
        public static string WeaponLegality {
            get {
                return ResourceManager.GetString("WeaponLegality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model oružja.
        /// </summary>
        public static string WeaponModel {
            get {
                return ResourceManager.GetString("WeaponModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite osnovne podatke o modelu oružja..
        /// </summary>
        public static string WeaponModelFormDescription {
            get {
                return ResourceManager.GetString("WeaponModelFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modeli oružja.
        /// </summary>
        public static string WeaponModels {
            get {
                return ResourceManager.GetString("WeaponModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje modelima oružja, proizvođačima, kalibrima i slikama..
        /// </summary>
        public static string WeaponModelsDescription {
            get {
                return ResourceManager.GetString("WeaponModelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija oružja.
        /// </summary>
        public static string WeaponsRegistration {
            get {
                return ResourceManager.GetString("WeaponsRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanje oružja.
        /// </summary>
        public static string WeaponState {
            get {
                return ResourceManager.GetString("WeaponState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status oružja.
        /// </summary>
        public static string WeaponStatus {
            get {
                return ResourceManager.GetString("WeaponStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Statusi oružja.
        /// </summary>
        public static string WeaponStatuses {
            get {
                return ResourceManager.GetString("WeaponStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje statusima oružja..
        /// </summary>
        public static string WeaponStatusesDescription {
            get {
                return ResourceManager.GetString("WeaponStatusesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite osnovne podatke o statusu oružja..
        /// </summary>
        public static string WeaponStatusFormDescription {
            get {
                return ResourceManager.GetString("WeaponStatusFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip oružja.
        /// </summary>
        public static string WeaponType {
            get {
                return ResourceManager.GetString("WeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite osnovne podatke o tipu oružja.
        /// </summary>
        public static string WeaponTypeFormDescription {
            get {
                return ResourceManager.GetString("WeaponTypeFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi oružja.
        /// </summary>
        public static string WeaponTypes {
            get {
                return ResourceManager.GetString("WeaponTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje šifarnikom tipova oružja.
        /// </summary>
        public static string WeaponTypesDescription {
            get {
                return ResourceManager.GetString("WeaponTypesDescription", resourceCulture);
            }
        }
    }
}
