//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset_management_Web_Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asset_management_Web_Core.Resources.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Weapons.
        /// </summary>
        public static string ActiveWeapons {
            get {
                return ResourceManager.GetString("ActiveWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add caliber.
        /// </summary>
        public static string AddCaliber {
            get {
                return ResourceManager.GetString("AddCaliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Evidence Item.
        /// </summary>
        public static string AddEvidenceItem {
            get {
                return ResourceManager.GetString("AddEvidenceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string AddLookupItem {
            get {
                return ResourceManager.GetString("AddLookupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add manufacturer.
        /// </summary>
        public static string AddManufacturer {
            get {
                return ResourceManager.GetString("AddManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Movement.
        /// </summary>
        public static string AddMovement {
            get {
                return ResourceManager.GetString("AddMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add weapon model.
        /// </summary>
        public static string AddWeaponModel {
            get {
                return ResourceManager.GetString("AddWeaponModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add weapon status.
        /// </summary>
        public static string AddWeaponStatus {
            get {
                return ResourceManager.GetString("AddWeaponStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Weapon Type.
        /// </summary>
        public static string AddWeaponType {
            get {
                return ResourceManager.GetString("AddWeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Band.
        /// </summary>
        public static string AgeBand {
            get {
                return ResourceManager.GetString("AgeBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Statuses.
        /// </summary>
        public static string AllStatuses {
            get {
                return ResourceManager.GetString("AllStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string AMSUser {
            get {
                return ResourceManager.GetString("AMSUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Stock.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Move No .
        /// </summary>
        public static string AuthMoveNo {
            get {
                return ResourceManager.GetString("AuthMoveNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorisation Data.
        /// </summary>
        public static string AuthorisationData {
            get {
                return ResourceManager.GetString("AuthorisationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorise.
        /// </summary>
        public static string Authorise {
            get {
                return ResourceManager.GetString("Authorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorised At.
        /// </summary>
        public static string AuthorisedAt {
            get {
                return ResourceManager.GetString("AuthorisedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorised By.
        /// </summary>
        public static string AuthorisedBy {
            get {
                return ResourceManager.GetString("AuthorisedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorise weapon move.
        /// </summary>
        public static string AuthoriseWeaponMove {
            get {
                return ResourceManager.GetString("AuthoriseWeaponMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorise Weapon Move Description.
        /// </summary>
        public static string AuthoriseWeaponMoveDescription {
            get {
                return ResourceManager.GetString("AuthoriseWeaponMoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to data capture.
        /// </summary>
        public static string BackToDataCapture {
            get {
                return ResourceManager.GetString("BackToDataCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Deposit.
        /// </summary>
        public static string BackToDeposit {
            get {
                return ResourceManager.GetString("BackToDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrel Mark.
        /// </summary>
        public static string BarrelMark {
            get {
                return ResourceManager.GetString("BarrelMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookkeeping By.
        /// </summary>
        public static string BookkeepingBy {
            get {
                return ResourceManager.GetString("BookkeepingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttstock Mark.
        /// </summary>
        public static string ButtstockMark {
            get {
                return ResourceManager.GetString("ButtstockMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caliber.
        /// </summary>
        public static string Caliber {
            get {
                return ResourceManager.GetString("Caliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter basic caliber information..
        /// </summary>
        public static string CaliberFormDescription {
            get {
                return ResourceManager.GetString("CaliberFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibers.
        /// </summary>
        public static string Calibers {
            get {
                return ResourceManager.GetString("Calibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage caliber lookup data..
        /// </summary>
        public static string CalibersDescription {
            get {
                return ResourceManager.GetString("CalibersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Info Folder Path.
        /// </summary>
        public static string CaseInfoFolderPath {
            get {
                return ResourceManager.GetString("CaseInfoFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case No.
        /// </summary>
        public static string CaseNo {
            get {
                return ResourceManager.GetString("CaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case type.
        /// </summary>
        public static string CaseType {
            get {
                return ResourceManager.GetString("CaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Date.
        /// </summary>
        public static string CheckDate {
            get {
                return ResourceManager.GetString("CheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check History.
        /// </summary>
        public static string CheckHistory {
            get {
                return ResourceManager.GetString("CheckHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check state.
        /// </summary>
        public static string CheckState {
            get {
                return ResourceManager.GetString("CheckState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Weapon Status.
        /// </summary>
        public static string CheckWeaponStatus {
            get {
                return ResourceManager.GetString("CheckWeaponStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Weapon Status Description .
        /// </summary>
        public static string CheckWeaponStatusDescription {
            get {
                return ResourceManager.GetString("CheckWeaponStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmSerial.
        /// </summary>
        public static string ConfirmSerial {
            get {
                return ResourceManager.GetString("ConfirmSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current image.
        /// </summary>
        public static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        public static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Description.
        /// </summary>
        public static string DashboardDescription {
            get {
                return ResourceManager.GetString("DashboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Capture.
        /// </summary>
        public static string DataCapture {
            get {
                return ResourceManager.GetString("DataCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Capture Description.
        /// </summary>
        public static string DataCaptureDescription {
            get {
                return ResourceManager.GetString("DataCaptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Ownership .
        /// </summary>
        public static string DateOfOwnership {
            get {
                return ResourceManager.GetString("DateOfOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Evidence Deposit Question.
        /// </summary>
        public static string DeleteEvidenceDepositQuestion {
            get {
                return ResourceManager.GetString("DeleteEvidenceDepositQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Data.
        /// </summary>
        public static string DepositData {
            get {
                return ResourceManager.GetString("DepositData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Location.
        /// </summary>
        public static string DepositLocation {
            get {
                return ResourceManager.GetString("DepositLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Date.
        /// </summary>
        public static string DonationDate {
            get {
                return ResourceManager.GetString("DonationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Temporary Stock .
        /// </summary>
        public static string DonationTemporaryStock {
            get {
                return ResourceManager.GetString("DonationTemporaryStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor Agency.
        /// </summary>
        public static string DonorAgency {
            get {
                return ResourceManager.GetString("DonorAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor Contract No.
        /// </summary>
        public static string DonorContractNo {
            get {
                return ResourceManager.GetString("DonorContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Caliber.
        /// </summary>
        public static string EditCaliber {
            get {
                return ResourceManager.GetString("EditCaliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        public static string EditLookupItem {
            get {
                return ResourceManager.GetString("EditLookupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit manufacturer.
        /// </summary>
        public static string EditManufacturer {
            get {
                return ResourceManager.GetString("EditManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Description.
        /// </summary>
        public static string EditUserDescription {
            get {
                return ResourceManager.GetString("EditUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit weapon model.
        /// </summary>
        public static string EditWeaponModel {
            get {
                return ResourceManager.GetString("EditWeaponModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit weapon status.
        /// </summary>
        public static string EditWeaponStatus {
            get {
                return ResourceManager.GetString("EditWeaponStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Weapon Type.
        /// </summary>
        public static string EditWeaponType {
            get {
                return ResourceManager.GetString("EditWeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User Certificate.
        /// </summary>
        public static string EndUserCertificate {
            get {
                return ResourceManager.GetString("EndUserCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code.
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Country.
        /// </summary>
        public static string EnterCountry {
            get {
                return ResourceManager.GetString("EnterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Description.
        /// </summary>
        public static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter display order.
        /// </summary>
        public static string EnterDisplayOrder {
            get {
                return ResourceManager.GetString("EnterDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name.
        /// </summary>
        public static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name.
        /// </summary>
        public static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence.
        /// </summary>
        public static string Evidence {
            get {
                return ResourceManager.GetString("Evidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence data.
        /// </summary>
        public static string EvidenceData {
            get {
                return ResourceManager.GetString("EvidenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup data for evidence, items, weapons, deposit locations and case types..
        /// </summary>
        public static string EvidenceDataDescription {
            get {
                return ResourceManager.GetString("EvidenceDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Deposit.
        /// </summary>
        public static string EvidenceDeposit {
            get {
                return ResourceManager.GetString("EvidenceDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Deposit Description.
        /// </summary>
        public static string EvidenceDepositDescription {
            get {
                return ResourceManager.GetString("EvidenceDepositDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence deposit locations.
        /// </summary>
        public static string EvidenceDepositLocation {
            get {
                return ResourceManager.GetString("EvidenceDepositLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Deposits.
        /// </summary>
        public static string EvidenceDeposits {
            get {
                return ResourceManager.GetString("EvidenceDeposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Deposits Description.
        /// </summary>
        public static string EvidenceDepositsDescription {
            get {
                return ResourceManager.GetString("EvidenceDepositsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence indicators.
        /// </summary>
        public static string EvidenceIndicator {
            get {
                return ResourceManager.GetString("EvidenceIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Items.
        /// </summary>
        public static string EvidenceItems {
            get {
                return ResourceManager.GetString("EvidenceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Management.
        /// </summary>
        public static string EvidenceManagement {
            get {
                return ResourceManager.GetString("EvidenceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Move History.
        /// </summary>
        public static string EvidenceMoveHistory {
            get {
                return ResourceManager.GetString("EvidenceMoveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence weapons.
        /// </summary>
        public static string EvidenceWeapon {
            get {
                return ResourceManager.GetString("EvidenceWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence weapon types.
        /// </summary>
        public static string EvidenceWeaponType {
            get {
                return ResourceManager.GetString("EvidenceWeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactorySerial.
        /// </summary>
        public static string FactorySerial {
            get {
                return ResourceManager.GetString("FactorySerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Location.
        /// </summary>
        public static string FromLocation {
            get {
                return ResourceManager.GetString("FromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Agencies.
        /// </summary>
        public static string GovernmentAgencies {
            get {
                return ResourceManager.GetString("GovernmentAgencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GovernmentAgency.
        /// </summary>
        public static string GovernmentAgency {
            get {
                return ResourceManager.GetString("GovernmentAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling Officer.
        /// </summary>
        public static string HandlingOfficer {
            get {
                return ResourceManager.GetString("HandlingOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder Info .
        /// </summary>
        public static string HolderInfo {
            get {
                return ResourceManager.GetString("HolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id No.
        /// </summary>
        public static string IdNo {
            get {
                return ResourceManager.GetString("IdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Type .
        /// </summary>
        public static string IdType {
            get {
                return ResourceManager.GetString("IdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory No .
        /// </summary>
        public static string InventoryNo {
            get {
                return ResourceManager.GetString("InventoryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is CoCriminal Offence.
        /// </summary>
        public static string IsCoCriminalOffence {
            get {
                return ResourceManager.GetString("IsCoCriminalOffence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Gender Based Violence .
        /// </summary>
        public static string IsGenderBasedViolence {
            get {
                return ResourceManager.GetString("IsGenderBasedViolence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Items .
        /// </summary>
        public static string LookupItems {
            get {
                return ResourceManager.GetString("LookupItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage values for the selected lookup category..
        /// </summary>
        public static string LookupItemsDescription {
            get {
                return ResourceManager.GetString("LookupItemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture Date.
        /// </summary>
        public static string ManufactureDate {
            get {
                return ResourceManager.GetString("ManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Country .
        /// </summary>
        public static string ManufacturerCountry {
            get {
                return ResourceManager.GetString("ManufacturerCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter basic manufacturer information..
        /// </summary>
        public static string ManufacturerFormDescription {
            get {
                return ResourceManager.GetString("ManufacturerFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        public static string Manufacturers {
            get {
                return ResourceManager.GetString("Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage weapon manufacturer lookup data..
        /// </summary>
        public static string ManufacturersDescription {
            get {
                return ResourceManager.GetString("ManufacturersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture year.
        /// </summary>
        public static string ManufactureYear {
            get {
                return ResourceManager.GetString("ManufactureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked Weapons.
        /// </summary>
        public static string MarkedWeapons {
            get {
                return ResourceManager.GetString("MarkedWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkingData.
        /// </summary>
        public static string MarkingData {
            get {
                return ResourceManager.GetString("MarkingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking History.
        /// </summary>
        public static string MarkingHistory {
            get {
                return ResourceManager.GetString("MarkingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking Label Text.
        /// </summary>
        public static string MarkingLabelText {
            get {
                return ResourceManager.GetString("MarkingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking Text 1.
        /// </summary>
        public static string MarkingText1 {
            get {
                return ResourceManager.GetString("MarkingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking Text 2.
        /// </summary>
        public static string MarkingText2 {
            get {
                return ResourceManager.GetString("MarkingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking Text 3.
        /// </summary>
        public static string MarkingText3 {
            get {
                return ResourceManager.GetString("MarkingText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Location.
        /// </summary>
        public static string MarkLocation {
            get {
                return ResourceManager.GetString("MarkLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Locations.
        /// </summary>
        public static string MarkLocations {
            get {
                return ResourceManager.GetString("MarkLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Weapon.
        /// </summary>
        public static string MarkWeapon {
            get {
                return ResourceManager.GetString("MarkWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Weapon Description.
        /// </summary>
        public static string MarkWeaponDescription {
            get {
                return ResourceManager.GetString("MarkWeaponDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Image.
        /// </summary>
        public static string ModelImage {
            get {
                return ResourceManager.GetString("ModelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Action.
        /// </summary>
        public static string MoveAction {
            get {
                return ResourceManager.GetString("MoveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move authoriser names.
        /// </summary>
        public static string MoveAuthoriserNames {
            get {
                return ResourceManager.GetString("MoveAuthoriserNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Data.
        /// </summary>
        public static string MoveData {
            get {
                return ResourceManager.GetString("MoveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Date.
        /// </summary>
        public static string MoveDate {
            get {
                return ResourceManager.GetString("MoveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved By.
        /// </summary>
        public static string MovedBy {
            get {
                return ResourceManager.GetString("MovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved weapon locations.
        /// </summary>
        public static string MovedWeaponLocation {
            get {
                return ResourceManager.GetString("MovedWeaponLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move evidence purpose.
        /// </summary>
        public static string MoveEvidencePurpose {
            get {
                return ResourceManager.GetString("MoveEvidencePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move History.
        /// </summary>
        public static string MoveHistory {
            get {
                return ResourceManager.GetString("MoveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Actions.
        /// </summary>
        public static string MovementActions {
            get {
                return ResourceManager.GetString("MovementActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Data.
        /// </summary>
        public static string MovementData {
            get {
                return ResourceManager.GetString("MovementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Data Description.
        /// </summary>
        public static string MovementDataDescription {
            get {
                return ResourceManager.GetString("MovementDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement History.
        /// </summary>
        public static string MovementHistory {
            get {
                return ResourceManager.GetString("MovementHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement Reasons.
        /// </summary>
        public static string MovementReasons {
            get {
                return ResourceManager.GetString("MovementReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Ordinal No.
        /// </summary>
        public static string MoveOrdinalNo {
            get {
                return ResourceManager.GetString("MoveOrdinalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Purpose.
        /// </summary>
        public static string MovePurpose {
            get {
                return ResourceManager.GetString("MovePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move status.
        /// </summary>
        public static string MoveStatus {
            get {
                return ResourceManager.GetString("MoveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narcotics.
        /// </summary>
        public static string Narcotics {
            get {
                return ResourceManager.GetString("Narcotics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deposit.
        /// </summary>
        public static string NewDeposit {
            get {
                return ResourceManager.GetString("NewDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Evidence Deposit.
        /// </summary>
        public static string NewEvidenceDeposit {
            get {
                return ResourceManager.GetString("NewEvidenceDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Location.
        /// </summary>
        public static string NewLocation {
            get {
                return ResourceManager.GetString("NewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Movement History Found.
        /// </summary>
        public static string NoMovementHistoryFound {
            get {
                return ResourceManager.GetString("NoMovementHistoryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- No organizational unit --.
        /// </summary>
        public static string NoOrganizationalUnit {
            get {
                return ResourceManager.GetString("NoOrganizationalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- No warehouse --.
        /// </summary>
        public static string NoWarehouse {
            get {
                return ResourceManager.GetString("NoWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No.
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Unit.
        /// </summary>
        public static string OrganizationalUnit {
            get {
                return ResourceManager.GetString("OrganizationalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Units.
        /// </summary>
        public static string OrganizationalUnits {
            get {
                return ResourceManager.GetString("OrganizationalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Data.
        /// </summary>
        public static string OrganizationData {
            get {
                return ResourceManager.GetString("OrganizationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Data Description.
        /// </summary>
        public static string OrganizationDataDescription {
            get {
                return ResourceManager.GetString("OrganizationDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Location.
        /// </summary>
        public static string OriginalLocation {
            get {
                return ResourceManager.GetString("OriginalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Locations.
        /// </summary>
        public static string OriginalLocations {
            get {
                return ResourceManager.GetString("OriginalLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original State.
        /// </summary>
        public static string OriginalState {
            get {
                return ResourceManager.GetString("OriginalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original States.
        /// </summary>
        public static string OriginalStates {
            get {
                return ResourceManager.GetString("OriginalStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Indicator.
        /// </summary>
        public static string OriginIndicator {
            get {
                return ResourceManager.GetString("OriginIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Indicators.
        /// </summary>
        public static string OriginIndicators {
            get {
                return ResourceManager.GetString("OriginIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Ownership.
        /// </summary>
        public static string OriginOwnership {
            get {
                return ResourceManager.GetString("OriginOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Id No .
        /// </summary>
        public static string PersonalIdNo {
            get {
                return ResourceManager.GetString("PersonalIdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Data.
        /// </summary>
        public static string PersonData {
            get {
                return ResourceManager.GetString("PersonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Marks .
        /// </summary>
        public static string PhysicalMarks {
            get {
                return ResourceManager.GetString("PhysicalMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Marking Job.
        /// </summary>
        public static string PrepareMarkingJob {
            get {
                return ResourceManager.GetString("PrepareMarkingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare weapon move.
        /// </summary>
        public static string PrepareWeaponMove {
            get {
                return ResourceManager.GetString("PrepareWeaponMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Weapon Move Description .
        /// </summary>
        public static string PrepareWeaponMoveDescription {
            get {
                return ResourceManager.GetString("PrepareWeaponMoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Deposit.
        /// </summary>
        public static string PrintDeposit {
            get {
                return ResourceManager.GetString("PrintDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Label.
        /// </summary>
        public static string PrintLabel {
            get {
                return ResourceManager.GetString("PrintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospective.
        /// </summary>
        public static string Prospective {
            get {
                return ResourceManager.GetString("Prospective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of use.
        /// </summary>
        public static string PurposeOfUse {
            get {
                return ResourceManager.GetString("PurposeOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query generator.
        /// </summary>
        public static string QueryGenerator {
            get {
                return ResourceManager.GetString("QueryGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Generator Description.
        /// </summary>
        public static string QueryGeneratorDescription {
            get {
                return ResourceManager.GetString("QueryGeneratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Results.
        /// </summary>
        public static string QueryResults {
            get {
                return ResourceManager.GetString("QueryResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brze akcije.
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Date.
        /// </summary>
        public static string ReceivedDate {
            get {
                return ResourceManager.GetString("ReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Checks.
        /// </summary>
        public static string RecentChecks {
            get {
                return ResourceManager.GetString("RecentChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Evidence Deposits.
        /// </summary>
        public static string RecentEvidenceDeposits {
            get {
                return ResourceManager.GetString("RecentEvidenceDeposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Authorised Moves.
        /// </summary>
        public static string RecentlyAuthorisedMoves {
            get {
                return ResourceManager.GetString("RecentlyAuthorisedMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Weapons.
        /// </summary>
        public static string RecentWeapons {
            get {
                return ResourceManager.GetString("RecentWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Weapon.
        /// </summary>
        public static string RegisterWeapon {
            get {
                return ResourceManager.GetString("RegisterWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Weapon Description .
        /// </summary>
        public static string RegisterWeaponDescription {
            get {
                return ResourceManager.GetString("RegisterWeaponDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Data .
        /// </summary>
        public static string RegistrationData {
            get {
                return ResourceManager.GetString("RegistrationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration No .
        /// </summary>
        public static string RegistrationNo {
            get {
                return ResourceManager.GetString("RegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen.
        /// </summary>
        public static string Reopen {
            get {
                return ResourceManager.GetString("Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Query.
        /// </summary>
        public static string RunQuery {
            get {
                return ResourceManager.GetString("RunQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Deposit.
        /// </summary>
        public static string SaveDeposit {
            get {
                return ResourceManager.GetString("SaveDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Only.
        /// </summary>
        public static string SaveOnly {
            get {
                return ResourceManager.GetString("SaveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Weapon.
        /// </summary>
        public static string SaveWeapon {
            get {
                return ResourceManager.GetString("SaveWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search options.
        /// </summary>
        public static string SearchOptions {
            get {
                return ResourceManager.GetString("SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Weapon Placeholder.
        /// </summary>
        public static string SearchWeaponPlaceholder {
            get {
                return ResourceManager.GetString("SearchWeaponPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select caliber --.
        /// </summary>
        public static string SelectCaliber {
            get {
                return ResourceManager.GetString("SelectCaliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select country --.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Weapon.
        /// </summary>
        public static string SelectedWeapon {
            get {
                return ResourceManager.GetString("SelectedWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Weapon Move .
        /// </summary>
        public static string SelectedWeaponMove {
            get {
                return ResourceManager.GetString("SelectedWeaponMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select manufacturer --.
        /// </summary>
        public static string SelectManufacturer {
            get {
                return ResourceManager.GetString("SelectManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Move From List.
        /// </summary>
        public static string SelectMoveFromList {
            get {
                return ResourceManager.GetString("SelectMoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select option --.
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select role --.
        /// </summary>
        public static string SelectRole {
            get {
                return ResourceManager.GetString("SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Weapon From List.
        /// </summary>
        public static string SelectWeaponFromList {
            get {
                return ResourceManager.GetString("SelectWeaponFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Weapon Model.
        /// </summary>
        public static string SelectWeaponModel {
            get {
                return ResourceManager.GetString("SelectWeaponModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select weapon type --.
        /// </summary>
        public static string SelectWeaponType {
            get {
                return ResourceManager.GetString("SelectWeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Mark.
        /// </summary>
        public static string SlideMark {
            get {
                return ResourceManager.GetString("SlideMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status And Additional.
        /// </summary>
        public static string StatusAndAdditional {
            get {
                return ResourceManager.GetString("StatusAndAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Order Date.
        /// </summary>
        public static string StorageOrderDate {
            get {
                return ResourceManager.GetString("StorageOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Order No.
        /// </summary>
        public static string StorageOrderNo {
            get {
                return ResourceManager.GetString("StorageOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted By Officer.
        /// </summary>
        public static string SubmittedByOfficer {
            get {
                return ResourceManager.GetString("SubmittedByOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Stock.
        /// </summary>
        public static string TempStock {
            get {
                return ResourceManager.GetString("TempStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Location.
        /// </summary>
        public static string ToLocation {
            get {
                return ResourceManager.GetString("ToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Checks.
        /// </summary>
        public static string TotalChecks {
            get {
                return ResourceManager.GetString("TotalChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weapons.
        /// </summary>
        public static string TotalWeapons {
            get {
                return ResourceManager.GetString("TotalWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPlaceholder.
        /// </summary>
        public static string UnitPlaceholder {
            get {
                return ResourceManager.GetString("UnitPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmarked Weapons.
        /// </summary>
        public static string UnmarkedWeapons {
            get {
                return ResourceManager.GetString("UnmarkedWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Filters To Run Query.
        /// </summary>
        public static string UseFiltersToRunQuery {
            get {
                return ResourceManager.GetString("UseFiltersToRunQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Org Name.
        /// </summary>
        public static string UserOrgName {
            get {
                return ResourceManager.GetString("UserOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Columns.
        /// </summary>
        public static string VisibleColumns {
            get {
                return ResourceManager.GetString("VisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        public static string Warehouses {
            get {
                return ResourceManager.GetString("Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Check Form.
        /// </summary>
        public static string WeaponCheckForm {
            get {
                return ResourceManager.GetString("WeaponCheckForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Data.
        /// </summary>
        public static string WeaponData {
            get {
                return ResourceManager.GetString("WeaponData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Data Description .
        /// </summary>
        public static string WeaponDataDescription {
            get {
                return ResourceManager.GetString("WeaponDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeaponIdentity.
        /// </summary>
        public static string WeaponIdentity {
            get {
                return ResourceManager.GetString("WeaponIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon item type.
        /// </summary>
        public static string WeaponItemType {
            get {
                return ResourceManager.GetString("WeaponItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon legality.
        /// </summary>
        public static string WeaponLegality {
            get {
                return ResourceManager.GetString("WeaponLegality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeaponModel.
        /// </summary>
        public static string WeaponModel {
            get {
                return ResourceManager.GetString("WeaponModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter basic weapon model information..
        /// </summary>
        public static string WeaponModelFormDescription {
            get {
                return ResourceManager.GetString("WeaponModelFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Models.
        /// </summary>
        public static string WeaponModels {
            get {
                return ResourceManager.GetString("WeaponModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage weapon models, manufacturers, calibers and images..
        /// </summary>
        public static string WeaponModelsDescription {
            get {
                return ResourceManager.GetString("WeaponModelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons Awaiting Authorisation.
        /// </summary>
        public static string WeaponsAwaitingAuthorisation {
            get {
                return ResourceManager.GetString("WeaponsAwaitingAuthorisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Registration.
        /// </summary>
        public static string WeaponsRegistration {
            get {
                return ResourceManager.GetString("WeaponsRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon state.
        /// </summary>
        public static string WeaponState {
            get {
                return ResourceManager.GetString("WeaponState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Status.
        /// </summary>
        public static string WeaponStatus {
            get {
                return ResourceManager.GetString("WeaponStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Statuses.
        /// </summary>
        public static string WeaponStatuses {
            get {
                return ResourceManager.GetString("WeaponStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage weapon status lookup data..
        /// </summary>
        public static string WeaponStatusesDescription {
            get {
                return ResourceManager.GetString("WeaponStatusesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter basic weapon status information..
        /// </summary>
        public static string WeaponStatusFormDescription {
            get {
                return ResourceManager.GetString("WeaponStatusFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon type.
        /// </summary>
        public static string WeaponType {
            get {
                return ResourceManager.GetString("WeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Type Form Description.
        /// </summary>
        public static string WeaponTypeFormDescription {
            get {
                return ResourceManager.GetString("WeaponTypeFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Types.
        /// </summary>
        public static string WeaponTypes {
            get {
                return ResourceManager.GetString("WeaponTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Types Description.
        /// </summary>
        public static string WeaponTypesDescription {
            get {
                return ResourceManager.GetString("WeaponTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
