<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Asset_management_Web_Core-3fbf472f-cc7f-4c93-9050-27e97b23fb87</UserSecretsId>
    <RootNamespace>Asset_management_Web_Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Helpers\CultureHelper.cs" />
    <Content Include="Helpers\CultureMiddleware.cs" />
    <Content Include="Helpers\ResourcesHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.23" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AMS data\AMS data.csproj" />
    <ProjectReference Include="..\AMS services\AMS services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Identity\Data\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\bs.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>bs.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\en.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>en.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\bs.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>bs.Designer.cs</LastGenOutput>
      <CustomToolNamespace>Asset_management_Web_Core.Resources</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\en.resx">
      <CustomToolNamespace>Asset_management_Web_Core.Resources</CustomToolNamespace>
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>en.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
