<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>AMS_DeviceAgent</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FlaUI.Core" Version="5.0.0" />
    <PackageReference Include="FlaUI.UIA2" Version="5.0.0" />
    <PackageReference Include="FlaUI.UIA3" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
    <PackageReference Include="System.Management" Version="10.0.8" />
    <PackageReference Include="System.Net.Http.Json" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AMS data\AMS data.csproj" />
    <ProjectReference Include="..\AMS services\AMS services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UIAutomationClient">
      <HintPath>$(WINDIR)\Microsoft.NET\Framework\v4.0.30319\UIAutomationClient.dll</HintPath>
    </Reference>

    <Reference Include="UIAutomationTypes">
      <HintPath>$(WINDIR)\Microsoft.NET\Framework\v4.0.30319\UIAutomationTypes.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
  <Reference Include="UIAutomationClient">
    <HintPath>C:\Windows\Microsoft.NET\Framework\v4.0.30319\UIAutomationClient.dll</HintPath>
  </Reference>

  <Reference Include="UIAutomationTypes">
    <HintPath>C:\Windows\Microsoft.NET\Framework\v4.0.30319\UIAutomationTypes.dll</HintPath>
  </Reference>
</ItemGroup>

</Project>